---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for install
  become: yes
  stat:
    path: '{{ sonarqube_install_dir }}'
  changed_when: False
  register: sonarqube_binary
- when: not sonarqube_binary.stat.exists
  block:
    - name: downloading...
      become: yes
      become_user: root
      get_url:
        url: '{{ sonarqube_url }}'
        dest: /tmp/{{ sonarqube_zip }}
        checksum: '{{ sonarqube_checksum }}'
        mode: 0644
    - name: unarchive
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: /tmp/{{ sonarqube_zip }}
        dest: '{{ sonarqube_parent_install_dir }}'
        creates: '{{ sonarqube_install_dir }}'
  always:
    - name: cleanup
      become: yes
      become_user: root
      file:
        path: /tmp/{{ sonarqube_zip }}
        state: absent
- name: link
  become: yes
  become_user: root
  file:
    src: '{{ sonarqube_install_dir }}'
    dest: '{{ sonarqube_link_dir }}'
    state: link
- name: add to default shell path
  become: yes
  become_user: root
  with_items:
    - f: sonarqube.sh
      d: /etc/profile.d
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("0644") }}'
